name: Automated Testing

on: 
  push:
  workflow_dispatch:  
  schedule:
    - cron: '0 10 * * 1'  

jobs:
   Nightwatch_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache npm modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Setting up environment variables
      - name: Set up environment variables
        run: |
          echo "USER_NAME=${{ secrets.USER_NAME }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
          echo "Base_url=${{ secrets.Base_url }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t nightwatch-test .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Nightwatch tests in Docker container
        run: |
          docker run --env USER_NAME=${{ secrets.USER_NAME }} --env PASSWORD=${{ secrets.PASSWORD }} --env Base_url=${{ secrets.Base_url }} nightwatch-test

      - name: Push Docker image to Docker Hub
        run: |
          docker push nightwatch-test

      - name: Archive test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: tests_output
